spring:
  profiles:
    active: dev #指定使用的yml文件
  thymeleaf:
    cache: false #禁用thymeleaf的缓存
    mode: HTML
server:
  port: 8080

mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
